export type BlogPost = {
  title: string;
  slug: string;
  excerpt: string;
  date: string;
  author: string;
  category: string;
  image?: string;
  body: string[];
};

export const blogPosts: BlogPost[] = [
  {
    title: "What is Pelvic Floor Physiotherapy? A Guide for Prenatal and Postpartum Care",
    slug: "what-is-pelvic-floor-physiotherapy",
    excerpt: "Pelvic floor physiotherapy helps women manage common prenatal and postpartum issues like incontinence and prolapse. Learn how this specialized treatment can support your recovery.",
    date: "2026-02-10",
    author: "Cherie Kuo, PT, PhD",
    category: "Pelvic Health",
    image: "/images/watercolor-mountain-bg.jpg",
    body: [
      "Pregnancy and childbirth are transformative experiences that place significant demands on a woman's body—particularly the pelvic floor. Pelvic floor physiotherapy is a specialized form of treatment that helps women address common issues that arise during pregnancy and after delivery, including incontinence, pelvic organ prolapse, and pelvic pain.",
      "**What is the Pelvic Floor?**",
      "The pelvic floor is a group of muscles, ligaments, and connective tissues that form a supportive hammock at the base of your pelvis. These muscles support your bladder, uterus, and bowel, and play a crucial role in bladder and bowel control, sexual function, and core stability.",
      "During pregnancy, the growing baby places increasing pressure on the pelvic floor. Hormonal changes also cause the tissues to become more relaxed in preparation for delivery. Vaginal birth can stretch or injure these muscles, while cesarean delivery can also affect pelvic floor function due to the pregnancy itself and abdominal surgery.",
      "**Common Prenatal and Postpartum Pelvic Floor Issues**",
      "**Urinary Incontinence** – Leaking urine when you cough, sneeze, laugh, or exercise is extremely common during and after pregnancy. This is called stress urinary incontinence and occurs when the pelvic floor muscles are weakened or stretched.",
      "**Pelvic Organ Prolapse** – When the pelvic floor muscles become too weak to support the pelvic organs, one or more organs may descend into the vaginal canal. Symptoms include a feeling of heaviness or pressure in the pelvis, a bulge at the vaginal opening, or difficulty emptying the bladder or bowels.",
      "**Pelvic Pain** – Pain in the pelvis, lower back, hips, or tailbone can occur during pregnancy due to postural changes and ligament laxity. Postpartum pelvic pain may result from birth trauma, scar tissue, or muscle imbalances.",
      "**Diastasis Recti** – This is the separation of the abdominal muscles that commonly occurs during pregnancy. While not strictly a pelvic floor issue, it often occurs alongside pelvic floor dysfunction and is addressed in pelvic floor physiotherapy.",
      "**How Pelvic Floor Physiotherapy Helps**",
      "A pelvic floor physiotherapist is trained to assess and treat these conditions using evidence-based techniques. Treatment may include:",
      "• **Internal and external assessment** – A thorough evaluation of pelvic floor muscle strength, coordination, and tone to identify areas of weakness or tension.",
      "• **Pelvic floor exercises** – Customized exercises (often called Kegels) to strengthen weak muscles or release tight muscles. Proper technique is essential—many women perform Kegels incorrectly without guidance.",
      "• **Manual therapy** – Hands-on techniques to release tight muscles, mobilize scar tissue (including cesarean or perineal scars), and improve tissue mobility.",
      "• **Education** – Guidance on bladder habits, posture, lifting techniques, and safe return to exercise postpartum.",
      "• **Core rehabilitation** – Exercises to restore core strength and coordination, including addressing diastasis recti.",
      "• **Pessary fitting** – For prolapse, a pessary (a supportive device inserted into the vagina) may be recommended and fitted by a trained physiotherapist.",
      "**When Should You See a Pelvic Floor Physiotherapist?**",
      "Ideally, every woman should have a pelvic floor assessment during pregnancy and again at 6-8 weeks postpartum. However, you should seek help sooner if you experience:",
      "• Leaking urine or stool",
      "• A feeling of heaviness or bulging in the vagina",
      "• Pain during intercourse",
      "• Persistent pelvic, hip, or lower back pain",
      "• Difficulty emptying your bladder or bowels",
      "**You Don't Have to Live With These Symptoms**",
      "Many women believe that incontinence and pelvic discomfort are just a normal part of having children. While these issues are common, they are not something you have to accept. Pelvic floor physiotherapy is highly effective, and most women see significant improvement with proper treatment.",
      "If you're pregnant or postpartum and experiencing any of these symptoms, book an appointment for a comprehensive pelvic floor assessment. Early intervention leads to better outcomes and helps you return to the activities you love with confidence.",
    ],
  },
  {
    title: "Understanding Tennis Elbow: Causes, Symptoms, and Treatment",
    slug: "understanding-tennis-elbow",
    excerpt: "Tennis elbow is a common overuse injury that affects more than just tennis players. Learn about its causes, symptoms, and effective treatment options.",
    date: "2026-01-21",
    author: "Cherie Kuo, PT, PhD",
    category: "Musculoskeletal Injury",
    image: "/images/blog-elbow.jpg",
    body: [
      "Tennis elbow, medically known as lateral epicondylitis, is a painful condition affecting the outer part of the elbow. Despite its name, you don't have to play tennis to develop this condition—it can affect anyone who performs repetitive gripping or wrist movements.",
      "**What Causes Tennis Elbow?**",
      "Tennis elbow occurs when the tendons that attach to the lateral epicondyle (the bony bump on the outside of your elbow) become irritated. This typically happens due to repetitive motions such as gripping a racquet, using a computer mouse, typing, or even carrying heavy bags.",
      "**Common Symptoms:**",
      "• Pain or burning on the outer part of the elbow",
      "• Weak grip strength",
      "• Pain that worsens when gripping objects, shaking hands, or turning a doorknob",
      "• Stiffness in the elbow, especially in the morning",
      "• Pain that may radiate down the forearm",
      "**How Physiotherapy Can Help:**",
      "Physiotherapy is highly effective for treating tennis elbow. Treatment typically includes:",
      "• Manual therapy – Soft tissue release and joint mobilization to reduce pain and improve mobility.",
      "• Dry needling – Targeting trigger points in the forearm muscles to release tension and promote healing.",
      "• Strengthening exercises – Progressive loading exercises to rebuild tendon strength and resilience.",
      "• Activity modification – Guidance on adjusting your daily activities and ergonomics to reduce strain on the elbow.",
      "• Bracing – A counterforce brace may be recommended to offload the tendon during activities.",
      "**Recovery Timeline:**",
      "With proper treatment, most people see significant improvement within 6-12 weeks. However, recovery time varies depending on the severity of the condition and how long symptoms have been present. Early intervention typically leads to faster recovery.",
      "If you're experiencing elbow pain that's affecting your daily activities, don't wait for it to worsen. Book an appointment for a thorough assessment and personalized treatment plan.",
    ],
  },
  {
    title: "5 Simple Stretches to Relieve Lower Back Pain",
    slug: "5-stretches-relieve-lower-back-pain",
    excerpt: "Lower back pain affects millions of people. Learn five effective stretches you can do at home to help reduce discomfort and improve mobility.",
    date: "2026-01-03",
    author: "Cherie Kuo, PT, PhD",
    category: "Pain Management",
    image: "/images/blog-back-pain.jpg",
    body: [
      "Lower back pain is one of the most common reasons people seek physiotherapy. Whether it's from sitting at a desk all day, lifting something heavy, or simply the wear and tear of daily life, back pain can significantly impact your quality of life.",
      "The good news is that many cases of lower back pain can be managed with simple stretches and exercises. Here are five stretches that can help relieve tension and improve flexibility in your lower back.",
      "**1. Cat-Cow Stretch** - Start on your hands and knees. Slowly arch your back up like a cat, then let it sag down while lifting your head. Repeat 10 times. This gentle movement helps mobilize the spine and relieve stiffness.",
      "**2. Child's Pose** - From a kneeling position, sit back on your heels and stretch your arms forward on the floor. Hold for 30-60 seconds. This stretch gently elongates the lower back muscles.",
      "**3. Knee-to-Chest Stretch** - Lie on your back and bring one knee toward your chest, holding it with both hands. Hold for 30-60 seconds, then switch legs. This helps release tension in the lower back and glutes.",
      "**4. Pelvic Tilts** - Lie on your back with knees bent and feet flat. Gently flatten your lower back against the floor by tightening your abdominal muscles. Hold for 5 seconds and repeat 10 times.",
      "**5. Thread the Needle** - Start on your hands and knees. Reach one arm under your body, sliding it along the floor while lowering your shoulder and head to the ground. Hold for 30-60 seconds, then switch sides. This stretch targets the upper and mid-back while gently releasing lower back tension.",
      "Importantly, if your pain is severe, persistent, or accompanied by other symptoms like numbness or weakness, it's important to consult with a physiotherapist for a proper assessment and personalized treatment plan.",
    ],
  },
  {
    title: "The Benefits of Dry Needling for Muscle Pain",
    slug: "benefits-dry-needling-muscle-pain",
    excerpt: "Dry needling is an effective treatment for muscle pain and trigger points. Discover how this technique works and what to expect during treatment.",
    date: "2025-12-10",
    author: "Cherie Kuo, PT, PhD",
    category: "Treatment Techniques",
    image: "/images/blog-needle2.jpg",
    body: [
      "If you've been dealing with persistent muscle pain or tightness, you may have heard about dry needling (or Intramuscular Stimulation/IMS) as a treatment option. This technique has gained popularity in physiotherapy for its effectiveness in treating muscle-related pain.",
      "**What is Dry Needling?**",
      "Dry needling involves inserting thin, sterile needles into trigger points—tight bands of muscle that can cause pain and restrict movement. Unlike acupuncture, which is based on traditional Chinese medicine, dry needling is grounded in Western medical principles and targets specific muscular issues.",
      "**How Does It Work?**",
      "When a needle is inserted into a trigger point, it can cause a local twitch response—a brief contraction of the muscle. This helps release the tight band, improve blood flow to the area, and reduce pain. The needle also stimulates the body's natural healing response.",
      "**Example Conditions Treated with Dry Needling:**",
      "• Neck and back pain",
      "• Shoulder pain and rotator cuff issues",
      "• Tennis elbow and golfer's elbow",
      "• Headaches and jaw pain",
      "• Hip and knee pain",
      "**What to Expect During Treatment:**",
      "During a dry needling session, you may feel a brief pinch as the needle is inserted, followed by a deep ache or twitch when the trigger point is reached. Most people find the treatment tolerable.",
      "After treatment, you may experience some soreness similar to post-exercise muscle ache. This usually resolves within 24-48 hours. Many patients notice improvement after just one or two sessions, though a series of treatments may be recommended for optimal results.",
    ],
  },
];
